version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '00:00'
    allow:
      - dependency-name: 'vue'
      - dependency-name: 'pinia'
      - dependency-name: 'vue-router'
