# @format

name: page

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: clone git
        uses: actions/checkout@v2
      - name: install nodejs
        uses: actions/setup-node@v3.0.0
        with:
          node-version: '16.x'
      - name: install
        run: |
          npm install pnpm -g
          pnpm install
          pnpm run play:build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.0.0
        with:
          target_branch: page
          build_dir: ./playground/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
